Tests articles users
JFer11/DjangoRestApp pull request #3
Opened 2021-02-19 00:13 UTC by JFer11

In this branch tests were added for the following ModelViewSets: "ArticleViewSet",  "UserViewSet" and "LoginCustomAuthToken".
In adittion, there were some changes to improve the quality of the code, like ArticleSerializer was change from Serializer to ModelSerializer, and more.

2021-02-25 14:30 UTC, joaquinco requested changes

2021-02-25 14:30 UTC, joaquinco commented on articles/app_articles/serializers.py
> +        validated_data['author'] = CustomUser.objects.get(username=self.context['request'].user.username)
Shouldn't you set the user.id to the author_id field? like `validated_data['author_id'] = request.user.id`

2021-02-25 14:30 UTC, joaquinco commented on articles/app_articles/tests/tests_articles.py
> +        Article.objects.all().delete()
You shouldn't do this manually.  Each test runs within a transaction that is rolled back.

I suggest you use the instance method `setuUp` that it runs within the test transaction.

2021-02-25 14:30 UTC, joaquinco commented on articles/app_articles/tests/tests_articles.py
> +            "is_staff": True
You might want to look into faker library: https://faker.readthedocs.io/en/master/

2021-02-25 14:30 UTC, joaquinco commented on articles/app_articles/tests/tests_articles.py
> +            self.all_articles.append(response.json())
you might want to look at https://github.com/FactoryBoy/factory_boy

2021-02-25 14:30 UTC, joaquinco commented on articles/app_articles/tests/tests_articles.py
> +        cls.token = response.json()['token']
This is repeated in every TestCase class, maybe there's a way to put it in a single place

2021-02-25 14:30 UTC, joaquinco commented on articles/app_articles/tests/tests_users.py
> +        pass
You can remove this method

2021-02-25 14:30 UTC, joaquinco commented on articles/app_articles/tests/tests_articles.py
> +        self.assertEqual(update_field['text'], response.json()['text'])
Can you add a test for articles edit permissions? I mean to check that only the author or admin can edit it (or the permissions you've defined).

2021-02-25 16:45 UTC, JFer11 commented on articles/app_articles/serializers.py
> +        validated_data['author'] = CustomUser.objects.get(username=self.context['request'].user.username)
Not really, I decided to use the username instead as it is also unique. However, I realize that that query is unnecessary, I already have the user.

2021-02-25 16:48 UTC, JFer11 commented on articles/app_articles/tests/tests_articles.py
> +            "is_staff": True
Thanks a lot! I did not know it.

2021-02-25 16:48 UTC, JFer11 commented on articles/app_articles/tests/tests_articles.py
> +            self.all_articles.append(response.json())
Thanks a lot! I did not know it

2021-02-25 16:58 UTC, JFer11 commented on articles/app_articles/tests/tests_users.py
> +        pass
Removed!

2021-02-25 16:58 UTC, joaquinco commented on articles/app_articles/serializers.py
> +        validated_data['author'] = CustomUser.objects.get(username=self.context['request'].user.username)
The primary key of CustomUser is the id, and you've added a field `author = models.ForeignKey(CustomUser)` in the Article model, so this means the article table has an `author_id` column of the same type as CustomUser's primary key. So I guess this code is not doing what you expect.

2021-02-25 17:04 UTC, JFer11 commented on articles/app_articles/tests/tests_articles.py
> +        self.assertEqual(update_field['text'], response.json()['text'])
Yes, would be a great idea.

2021-02-25 17:07 UTC, JFer11 commented on articles/app_articles/tests/tests_articles.py
> +        cls.token = response.json()['token']
Yes, there are few cases where "Pablo" is admin and where is not. But it can be improved.

2021-02-26 15:40 UTC, JFer11 commented on articles/app_articles/tests/tests_articles.py
> +        Article.objects.all().delete()
Okey, I will change it in the next PR.

2021-02-26 15:41 UTC, merged